### ISSUE TITLE
Update Wp-Pro-Quiz to Wp-Adv-Quiz

### ISSUE THREAD

**Issue by gerard-merkator** [markusbegerow/Wp-Adv-Quiz#4]
Hello, Markus!
I use Wp-Pro-Quiz plugin a long time. I have many quizzes on my website. Can i update Wp-Pro-Quiz to Wp-Adv-Quiz without losing my quizzes and questions? And how i can do it?

**Comment by markusbegerow** [comment]
Hey @gerard-merkator,
I have migrated all my quizzes with the old export function over xml into the new quiz successfully.
But please setup a dev-/test-system in order to test it.

Sometimes the wp-pro-quiz export function is a little bit buggy.
I think about to create a connector to provide a more compfortable way to import the old quizzes.

**Comment by gerard-merkator** [comment]
Export function over xml works well. Thanks!

**Comment by markusbegerow** [comment]
Your welcome...

**Comment by Makrele841** [comment]
Hey guys,

if I want to export as an XML file, I get this:

Fatal error: Array and string offset access syntax with curly braces is no longer supported in /homepages/14/d4295017746/htdocs/einfachmeditieren.net/wp-content/plugins/wp-pro-quiz/lib/helper/WpProQuiz_Helper_Until.php on line 122

Is there a way to solve this?
Thanks

**Comment by brandonc89** [comment]
I am also attempting to export my question/quiz data in XML format to upload to WP-Adv-Quiz however each time I export from Wp-Pro-Quiz I get a fatal error. Any help would be greatly appreciated as I can't seem to find any other info to help with this issue.

Thanks!
