### ISSUE TITLE
Wp-Adv-Quiz translation

### ISSUE THREAD

**Issue by gerard-merkator** [markusbegerow/Wp-Adv-Quiz#5]
A few years ago I translated Wp-Pro-Quiz plugin into Ukrainian. Is it possible to add this translation to Wp-Adv-Quiz plugin?

**Comment by markusbegerow** [comment]
Hey @gerard-merkator,

that's a good idea. I check the requirements and then you can provide your translation.

**Comment by varuthai** [comment]
i am thai people and i had a teacher, i love your plugin because i will use it to teach my students at online (beacuse of my univ is close covid)
so i try to translation your plugin Wp-Adv-QuizDevelopment (trunk)Thai on translate.wordpress.org
please update it i wait for thai version for thai education. Looking forward to the update.
thank alot
aj sittiporn pornudomthap
Uttaradit Rajabhat University, thailand
[https://translate.wordpress.org/projects/wp-plugins/advanced-quiz/dev/th/default/?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=waiting](https://translate.wordpress.org/projects/wp-plugins/advanced-quiz/dev/th/default/?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=waiting)

**Comment by markusbegerow** [comment]
Solution is comin'
