### ISSUE TITLE
html tag not working in incorrect answer

### ISSUE THREAD

**Issue by tozbey** [markusbegerow/Wp-Adv-Quiz#6]
Hi Markus!

I use Wp-Pro-Quiz plugin a long time. I'm trying your plugin on my staging page. I want to share some bugs I found:

- The html tags I added to the "Message with the incorrect answer(optional)" field don't work and the images do not appear.
- There was a problem while importing and not all exams were added.
- Although "Show category score" is turned off, it shows the score according to the category as a result of the exam.

**Comment by markusbegerow** [comment]
Hey @tozbey,

thanks for testing. I'll answer between your lines

- The html tags I added to the "Message with the incorrect answer(optional)" field don't work and the images do not appear.
  - In order to pass the WordPress review process I had to fix all security issues. Next step is to allow p,img tags and so on. Which tags would you allow to use?
- There was a problem while importing and not all exams were added.
  - Do you have any results or screenshots
- Although "Show category score" is turned off, it shows the score according to the category as a result of the exam.
  - I'll look into it.

Please open one issue for every bug or idea. It's very hard to collect or answer a bunch of questions. Thanks in advance...
