### ISSUE TITLE
Translation thailand complete

### ISSUE THREAD

**Issue by varuthai** [markusbegerow/Wp-Adv-Quiz#7]
i am thai people and i had a teacher, i love your plugin because i will use it to teach my students at online (beacuse of my univ is close covid)
so i try to translation your plugin Wp-Adv-QuizDevelopment (trunk)Thai on translate.wordpress.org
please update it i wait for thai version for thai education. Looking forward to the update.
thank alot
aj sittiporn pornudomthap
Uttaradit Rajabhat University, thailand
https://translate.wordpress.org/projects/wp-plugins/advanced-quiz/dev/th/default/?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=waiting

**Comment by markusbegerow** [comment]
Hey @varuthai,
thank you for your translation. 
I'll add this to the plugin and mention you as translator here on github.

Best regards
Markus

**Comment by gerard-merkator** [comment]
Hello, varuthai
To approve the translation you must contact the editor or become an editor yourself. In order to become an editor (PTE) of the translation of the WordPress plugin, you must make a request. 
Link to page 'Project Translation Editor (PTE) Request':
https://make.wordpress.org/polyglots/handbook/plugin-theme-authors-guide/pte-request/
Link to ไทย/Thai Translation Team:
https://make.wordpress.org/polyglots/teams/?locale=th

**Comment by markusbegerow** [comment]
Solution is comin'
